name: "[CD] Scafflater"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping package versions
        run: |
          npm run version --yes
      