name: "[CD] Scafflater"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  bump-versions:
    name: 'Bump packages version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-
      - name: Install dependencies
        run: |
          npm ci
      - name: Install dependencies
        run: |
          npm i -g @oclif/dev-cli
      - name: Bumping package versions
        run: |
          npm run version --yes
      