name: "[Release] Scafflater"

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  release-to-npmjs:
    name: "Releasing NPM Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.tag_name}}

      - name: Configure CI Git User
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Setup node 15.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x

      - name: Generate Types
        run: |
          npm run types

      - name: NPM Authentication
        run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publishing packages
      #   run: |
      #     npm publish --workspaces
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_PAT }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
